#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const root = process.cwd();
const DEFAULT_SERVICE_ACCOUNT_CANDIDATES = [
  './secure/firebase-service-account.json',
  './secure/service-account.json',
  './service-account.json',
];

function getArg(name) {
  const prefix = `--${name}=`;
  const found = process.argv.find((arg) => arg.startsWith(prefix));
  return found ? found.slice(prefix.length) : '';
}

function resolvePath(value) {
  if (!value) return '';
  return path.isAbsolute(value) ? value : path.join(root, value);
}

function setEnvValue(content, name, value) {
  const line = `${name}=${String(value)}`;
  const regex = new RegExp(`^${name}=.*$`, 'm');
  if (regex.test(content)) {
    return content.replace(regex, line);
  }
  if (!content.endsWith('\n')) {
    return `${content}\n${line}\n`;
  }
  return `${content}${line}\n`;
}

function fail(message) {
  console.error(`ERROR: ${message}`);
  console.error('Usage: node scripts/write_fcm_env.cjs [--service-account=path/to/service-account.json] [--file=.env.production]');
  console.error('Default service-account lookup order:');
  console.error('- GOOGLE_APPLICATION_CREDENTIALS (if set and file exists)');
  for (const candidate of DEFAULT_SERVICE_ACCOUNT_CANDIDATES) {
    console.error(`- ${candidate}`);
  }
  process.exit(1);
}

function resolveServiceAccountPath(serviceAccountArg) {
  if (serviceAccountArg) {
    const explicit = resolvePath(serviceAccountArg);
    if (fs.existsSync(explicit)) return explicit;
    return '';
  }

  const envCredentialsPath = process.env.GOOGLE_APPLICATION_CREDENTIALS && String(process.env.GOOGLE_APPLICATION_CREDENTIALS).trim();
  if (envCredentialsPath) {
    const resolvedEnvPath = resolvePath(envCredentialsPath);
    if (fs.existsSync(resolvedEnvPath)) {
      return resolvedEnvPath;
    }
  }

  for (const candidate of DEFAULT_SERVICE_ACCOUNT_CANDIDATES) {
    const resolved = resolvePath(candidate);
    if (fs.existsSync(resolved)) {
      return resolved;
    }
  }

  return '';
}

function run() {
  const serviceAccountArg = getArg('service-account');
  const targetFileArg = getArg('file') || '.env.production';
  const serviceAccountPath = resolveServiceAccountPath(serviceAccountArg);
  const targetPath = resolvePath(targetFileArg);

  if (!serviceAccountPath) {
    if (serviceAccountArg) {
      fail(`Service account file not found: ${resolvePath(serviceAccountArg)}`);
    }
    fail('No service account file found in default lookup paths');
  }

  let serviceAccount;
  try {
    serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'));
  } catch {
    fail('Service account file is not valid JSON');
  }

  const projectId = serviceAccount && typeof serviceAccount.project_id === 'string' ? serviceAccount.project_id.trim() : '';
  const clientEmail = serviceAccount && typeof serviceAccount.client_email === 'string' ? serviceAccount.client_email.trim() : '';
  const privateKey = serviceAccount && typeof serviceAccount.private_key === 'string' ? serviceAccount.private_key.trim() : '';

  if (!projectId) {
    fail('Service account JSON does not include project_id');
  }
  if (!clientEmail || !privateKey) {
    fail('Service account JSON is missing required credentials fields');
  }

  const inlineJson = JSON.stringify(serviceAccount);

  let content = '';
  if (fs.existsSync(targetPath)) {
    content = fs.readFileSync(targetPath, 'utf8');
  } else {
    content = '# Generated by scripts/write_fcm_env.cjs\n';
  }

  content = setEnvValue(content, 'FCM_PROJECT_ID', projectId);
  content = setEnvValue(content, 'FIREBASE_PROJECT_ID', projectId);
  content = setEnvValue(content, 'FCM_SERVICE_ACCOUNT_JSON', inlineJson);

  fs.writeFileSync(targetPath, content, 'utf8');

  console.log('FCM env values written successfully');
  console.log(`Target file: ${targetPath}`);
  console.log(`Service account source: ${serviceAccountPath}`);
  console.log(`FCM_PROJECT_ID=${projectId}`);
  console.log('FCM_SERVICE_ACCOUNT_JSON=<written>');
}

run();
