#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const webpush = require('web-push');

const root = process.cwd();
const fileArg = process.argv.find((arg) => arg.startsWith('--file='));
const targetFile = fileArg ? fileArg.slice('--file='.length) : '.env.production';
const targetPath = path.isAbsolute(targetFile) ? targetFile : path.join(root, targetFile);

const keys = webpush.generateVAPIDKeys();
const subject = process.env.VAPID_SUBJECT && String(process.env.VAPID_SUBJECT).trim()
  ? String(process.env.VAPID_SUBJECT).trim()
  : 'mailto:admin@classify.app';

function setEnvValue(content, name, value) {
  const escaped = value.replace(/\\/g, '\\\\');
  const line = `${name}=${escaped}`;
  const regex = new RegExp(`^${name}=.*$`, 'm');
  if (regex.test(content)) {
    return content.replace(regex, line);
  }
  if (!content.endsWith('\n')) {
    return `${content}\n${line}\n`;
  }
  return `${content}${line}\n`;
}

let content = '';
if (fs.existsSync(targetPath)) {
  content = fs.readFileSync(targetPath, 'utf8');
} else {
  content = '# Generated by scripts/write_vapid_env.cjs\n';
}

content = setEnvValue(content, 'VAPID_PUBLIC_KEY', keys.publicKey);
content = setEnvValue(content, 'VAPID_PRIVATE_KEY', keys.privateKey);
content = setEnvValue(content, 'VAPID_SUBJECT', subject);

fs.writeFileSync(targetPath, content, 'utf8');

console.log('VAPID keys generated and written successfully');
console.log(`Target file: ${targetPath}`);
console.log(`VAPID_PUBLIC_KEY=${keys.publicKey}`);
console.log(`VAPID_PRIVATE_KEY=${keys.privateKey}`);
console.log(`VAPID_SUBJECT=${subject}`);
